### ISSUE TITLE
Consider using Docker for CI Services

### ISSUE THREAD

**Issue by a-t-0** [HiveMinds/Productivity-setup#1]
The functionality here could be really cool to add into a docker image, that can then be checked-out on CI services. Refer to <a href="https://docs.docker.com/compose/gettingstarted/#step-2-create-a-dockerfile" rel="nofollow">Create a dockerfile</a> for more information. The custom docker image can then be accessed as follows for GitHub Actions <a href="https://stackoverflow.com/a/64051330/11989587" rel="nofollow">[1]</a>. However, depending on how long it takes to check-out the Docker image in the cloud it could be slower than the current implementation.

Ps. Original author of this comment: skilkis 
The issue was automatically copied into this new repository.

**Comment by a-t-0** [comment]
Thank you for having a look and suggesting how I can improve my work! It will be a few weeks before I look into your tip and I'll carefully evaluate it!

**Comment by mohitsaxenaknoldus** [comment]
Bookmarking to work on later.

**Comment by a-t-0** [comment]
Cool, this is not a hard requirement for me, but I would like to learn how to do this, and I think some people find this convenient, so I think it would be nice to support them.

**Comment by mohitsaxenaknoldus** [comment]
So what exactly do you mean by `using Docker for CI services`? Are we talking about creating a docker image for this project or just setting up Github actions with any docker image which can run the test?

**Comment by a-t-0** [comment]
@mohitsaxenaknoldus thank you for asking for clarification! Perhaps @skilkis could briefly elaborate on this. My guess is that it suggests creating a docker image for this project (and then setting up CI for this docker image). (Note this issue was originally raised by skilkis in an old copy of this repository (and automatically copied to this new repository (which is why the auther was me, instead of skilkis))).

However, this project heavily customises the actual Ubuntu installation, so in retrospect, I slightly doubt whether it makes sense to put that into a docker Image. I would guess the tw-install repository would be more suitable to be converted to/have a docker counterpart, because that actually installs and hosts some service, which I imagine, can be put into a docker.

However, as mentioned, this issue is low priority, so I would suggest moving on to another issue. Nevertheless, if @skilkis/someone can make a clear case for it, or can explain the added value of having the docker image, I would be interested.

**Comment by skilkis** [comment]
@mohitsaxenaknoldus @a-t-0 When I originally made the comment I believe the old repo might have been using Travis-CI and running all of the install scripts on base image of Ubuntu. Benefit of having Docker is that you get to customize a base image as you do now but avoid the install process on each machine. Assuming that the install time is slower than image check-out time, this can drastically reduce installation overhead.

Having only briefly looked into the `tests/` directory I believe most of the tests are to check the various installation scripts. If there are not much integration tests that check the environment at the end of an install, these unit tests might be of more benefit to you. In that case, only reason for Docker would be to have ready-to-go development environment similar to the approach VS Code takes for development environments. [1](https://code.visualstudio.com/docs/remote/containers)

However, indeed as @a-t-0 states Docker shines more when there is a service to host and you have tests that directly verify that the service works once it is up. When I made the original comment I misunderstood what this repo is about. I saw lots of install scripts and a running CI server and thought: "Gee lets optimize that with Docker". So no I don't think it's applicable here. Hopefully, that clears things up a bit :smile:

**Comment by a-t-0** [comment]
@skilkis Thank you for your clarification, elaboration and initial suggestion. Also the benefit of the Docker image to have a ready-to-go development environment is clear as you sketched it. I closed this issue and will keep the option in mind for alternative repositories, once they have been polished up to some basic release level.
